---
workflows:
  ios-workflow:
    name: iOS Native App
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        BUNDLE_ID: "com.cydiabwcx.app.JSQ"
        XCODE_WORKSPACE: "JSQ.xcodeproj"
        XCODE_SCHEME: "JSQ"
      groups:
        - app_store_credentials
      xcode: latest
      cocoapods: default
    # 移除 integrations 部分
    # integrations:
    #   app_store_connect: app_store_credentials
    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true
        - pattern: 'develop'
          include: true
          source: true
    scripts:
      - name: 设置 Keychain 用于代码签名
        script: |
          keychain initialize
      
      - name: 获取签名文件
        script: |
          # 设置详细日志输出
          set -x
          
          # 验证API连接
          echo "验证App Store Connect API连接..."
          app-store-connect get-latest-app-store-version $BUNDLE_ID || echo "API连接测试完成"
          
          # 列出现有证书
          echo "列出现有证书..."
          app-store-connect certificates list --type IOS_DISTRIBUTION || true
          
          # 尝试获取签名文件，如果失败则创建新的
          echo "尝试获取现有签名文件..."
          if ! app-store-connect fetch-signing-files $BUNDLE_ID --type IOS_APP_STORE; then
            echo "无法获取现有签名文件，创建新的签名文件..."
            app-store-connect fetch-signing-files $BUNDLE_ID \
              --type IOS_APP_STORE \
              --create
          fi
      
      - name: 设置代码签名设置
        script: |
          xcode-project use-profiles
      
      - name: 构建 iOS 应用
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    
    publishing:
      email:
        recipients:
          - gaozhenaax@163.com
        notify:
          success: true
          failure: true
      
      app_store_connect:
        # 使用环境变量认证
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER  
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: false
        submit_to_app_store: false
scripts:
  - name: 设置 Keychain 用于代码签名
    script: |
      keychain initialize
  
  - name: 获取签名文件
    script: |
      # 设置详细日志输出
      set -x
      
      # 列出现有证书
      echo "列出现有证书..."
      app-store-connect certificates list --type IOS_DISTRIBUTION
      
      # 撤销现有的iOS Distribution证书（如果存在）
      echo "撤销现有证书..."
      app-store-connect certificates delete --certificate-id BSQN86SNL8 || echo "证书撤销完成或不存在"
      
      # 创建新的签名文件和证书
      echo "创建新的签名文件和证书..."
      app-store-connect fetch-signing-files $BUNDLE_ID \
        --type IOS_APP_STORE \
        --create
