---
workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.cydiabwcx.app.JSQ
      vars:
        XCODE_PROJECT: "JSQ.xcodeproj"
        XCODE_SCHEME: "JSQ"
        APP_STORE_CONNECT_ISSUER_ID: Encrypted(...)
        APP_STORE_CONNECT_KEY_IDENTIFIER: Encrypted(...)
        APP_STORE_CONNECT_PRIVATE_KEY: Encrypted(...)
        CERTIFICATE_PASSWORD: Encrypted(...)
    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: develop
          include: true
          source: true
    scripts:
      - name: 初始化 Keychain
        script: |
          keychain initialize
      
      - name: 构建 iOS 应用
        script: |
          #!/usr/bin/env bash
          set -e
          
          # 创建构建目录
          mkdir -p build/ios/xcarchive
          mkdir -p build/ios/ipa
          
          # 使用自动签名构建，添加 -allowProvisioningUpdates 参数
          xcodebuild -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath build/ios/xcarchive/JSQ.xcarchive \
            archive \
            CODE_SIGN_STYLE=Automatic \
            DEVELOPMENT_TEAM=2D7HH6DNF4 \
            COMPILER_INDEX_STORE_ENABLE=NO \
            -allowProvisioningUpdates
          
          # 导出 IPA
          xcodebuild -exportArchive \
            -archivePath build/ios/xcarchive/JSQ.xcarchive \
            -exportPath build/ios/ipa \
            -exportOptionsPlist ExportOptions.plist
    
    artifacts:
      - build/ios/ipa/*.ipa
    
    publishing:
      email:
        recipients:
          - cydiabwcx@gmail.com
        notify:
          success: true
          failure: true
