Using Xcode 16.3 (16E140)
Check JSQ.xcodeproj build settings
Execute "xcodebuild -project JSQ.xcodeproj -scheme JSQ -config Release -showBuildSettings"

Archive JSQ.xcodeproj
Execute "xcodebuild -project JSQ.xcodeproj -scheme JSQ -config Release -archivePath /Users/builder/clone/build/ios/xcarchive/JSQ_rf4oua6n.xcarchive archive COMPILER_INDEX_STORE_ENABLE=NO CODE_SIGN_STYLE=Manual"


❌  /Users/builder/clone/JSQ.xcodeproj: error: "JSQ" requires a provisioning profile. Select a provisioning profile in the Signing & Capabilities editor. (in target 'JSQ' from project 'JSQ')


Failed to archive JSQ.xcodeproj


Build failed :|
Step 5 script `构建 iOS 应用` exited with status code 65
