name: iOS Build and Upload

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Latest Xcode
      run: |
        sudo xcode-select -switch /Applications/Xcode_16.1.app/Contents/Developer || \
        sudo xcode-select -switch /Applications/Xcode_16.0.app/Contents/Developer
        xcodebuild -version
    
    - name: Import Code-Signing Certificates
      uses: Apple-Actions/import-codesign-certs@v2
      with:
        p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
        p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}
    
    - name: Download Provisioning Profiles
      uses: Apple-Actions/download-provisioning-profiles@v1
      with:
        bundle-id: 'com.yourcompany.JSQ'  # 替换为您的Bundle ID
        issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
        api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
        api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}
    
    - name: Build Archive
      run: |
        xcodebuild archive \
          -project JSQ.xcodeproj \
          -scheme JSQ \
          -archivePath JSQ.xcarchive \
          -destination "generic/platform=iOS" \
          -configuration Release
    
    - name: Export IPA
      run: |
        xcodebuild -exportArchive \
          -archivePath JSQ.xcarchive \
          -exportPath . \
          -exportOptionsPlist ExportOptions.plist
    
    - name: Upload to App Store Connect
      run: |
        xcrun altool --upload-app \
          --type ios \
          --file *.ipa \
          --username "${{ secrets.APPSTORE_USERNAME }}" \
          --password "${{ secrets.APPSTORE_PASSWORD }}"
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: JSQ-ipa
        path: "*.ipa"